### ISSUE TITLE
Crafting can sometimes send your carrot count into the negative

### ISSUE THREAD

**Issue by not-the** [not-the/Carrot-Clicker#71] opened 2022-10-31 19:02 UTC
Steps to reproduce:
- Propane tank fully upgraded
- 1Q carrots available
- Craft a Hoe

May work with other setups, I haven't done any testing

**Comment by JJCVIP** [comment] 2022-11-07 13:15
The reason it stayed in the negatives is because the function was missing a call for the carrot count to update in whenDone(). The reason the Propane tank sends it so far into the negatives is because its value is at 64. Makes the amount to adjust way to large. Going to nerf it severely and might also try to make the crafting speed much slower right before it finishes

**Comment by JJCVIP** [comment] 2022-11-07 13:56
I believe that it is working as intended now. Closing the issue but will still require testing. The display for the effect of the propane tank looks stupid and will need fixing. Will assign to that to Kal because I am not sure where that information is pushed. If need be I can probably find it but I think it would be easier for him.

**Closed by JJCVIP** 2022-11-07 13:56 UTC
Labels: bug
